backend:
  name: github
  repo: vxzn/tqf_gadget # Sesuaikan nama repositori
  branch: main # Sesuaikan nama branch utama (main/master)

media_folder: "images/uploads" # Folder tempat foto yang diupload tersimpan
public_folder: "images/uploads"

collections:
  - name: "products"
    label: "Katalog Produk"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama Produk", name: "title", widget: "string" }
      - { label: "Brand", name: "brand", widget: "select", options: ["SAMSUNG", "XIAOMI", "APPLE", "POCO", "REALME", "VIVO", "OPPO", "INFINIX"] }
      - { label: "Harga (Rp)", name: "price", widget: "number", value_type: "int" }
      - { label: "Status", name: "status", widget: "select", options: ["READY", "SOLD OUT"] }
      - { label: "RAM / Internal", name: "ram_internal", widget: "string", placeholder: "8GB / 128GB" }
      - { label: "Kondisi", name: "condition", widget: "string", placeholder: "95% Mulus (Pemakaian Wajar)" }
      - { label: "Catatan QC / Kelengkapan", name: "qc_note", widget: "string", placeholder: "QC 100% Normal - Fullset Original" }
      - { label: "Foto Produk", name: "image", widget: "image" }
